# Generated by Django 4.1.7 on 2023-04-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataprovider",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dataprovider",
            name="name",
            field=models.CharField(max_length=24),
        ),
    ]
