# Generated by Django 4.1.7 on 2023-04-21 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0002_alter_dailydata_adj_close_alter_dailydata_close_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailydata",
            name="security",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_ownership",
                to="data.security",
            ),
        ),
        migrations.AlterField(
            model_name="monthlydata",
            name="security",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_ownership",
                to="data.security",
            ),
        ),
        migrations.AlterField(
            model_name="weeklydata",
            name="security",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_ownership",
                to="data.security",
            ),
        ),
    ]
