# Generated by Django 4.1.7 on 2023-04-27 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0003_alter_daily_options_alter_monthly_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="daily",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="monthly",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="weekly",
            options={"ordering": ["-date"]},
        ),
    ]
