# Generated by Django 4.1.7 on 2023-04-28 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0004_alter_daily_options_alter_monthly_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_%(app_label)s",
                        to="data.security",
                    ),
                ),
            ],
            options={
                "ordering": ["security"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MonthlyUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_%(app_label)s",
                        to="data.security",
                    ),
                ),
            ],
            options={
                "ordering": ["security"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DailyUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_%(app_label)s",
                        to="data.security",
                    ),
                ),
            ],
            options={
                "ordering": ["security"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="weeklyupdate",
            constraint=models.UniqueConstraint(
                fields=("security", "date"), name="unique_sec_update_weekly_combination"
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlyupdate",
            constraint=models.UniqueConstraint(
                fields=("security", "date"),
                name="unique_sec_update_monthly_combination",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyupdate",
            constraint=models.UniqueConstraint(
                fields=("security", "date"), name="unique_sec_update_daily_combination"
            ),
        ),
    ]
